#!/bin/bash -x
cd $PROJECTHOME
ssh -p ${SRV_PORT} vuiisdev@${SRV_IP} -- 'mkdir -p ~/.ssh && chmod 700 ~/.ssh && touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys'
cat ~/.ssh/id_rsa.pub | ssh -p ${SRV_PORT} vuiisdev@${SRV_IP} -- 'cat >> ~/.ssh/authorized_keys'
